In [1]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

from sklearn import ensemble

In [54]:
df2 = pd.read_csv("breastcancer.csv").dropna()

In [55]:
df2["Class"] = np.where(df2["Class"] == 4, 1,0)

In [56]:
df = df2.drop("Class", 1)

In [57]:
df.isna().any()

Id                             False
Clump_Thickness                False
Uniformity_Cell_Size           False
Uniformity_Cell_Shape          False
Marginal_Adhesion              False
Single_Epithelial_Cell_Size    False
Bare_Nuclei                    False
Bland_Chromatin                False
Normal_Nucleoli                False
Mitoses                        False
dtype: bool

In [62]:
df3 = df.drop("Id", 1)

In [72]:
from sklearn.linear_model import LogisticRegression
regr = LogisticRegression()

x = df
y = df2["Class"]

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=.2)

regr.fit(x_train, y_train)

print(regr.coef_)
print(regr.score(x_test,y_test))


[[-5.51755075e-07  7.82994992e-12  1.06192463e-11  1.02461628e-11
   8.57111259e-12  5.89397262e-12  1.29446635e-11  7.28593810e-12
   9.10924739e-12  2.79653019e-12]]
0.7007299270072993


In [89]:
x = df.iloc[:, [2,3,6,7]]
x_train, x_test, y_train, y_test = train_test_split(x, y , test_size=.2)

In [90]:
params = {"n_estimators" : 100,
         "max_depth" : 4}

regr2 = ensemble.RandomForestClassifier(** params)

regr2.fit(x_train, y_train)
pred = regr2.predict(x_test)

print(regr2.feature_importances_)
print(regr2.score(x_test, y_test))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(pred, y_test))

[0.36858039 0.32505948 0.15185161 0.15450851]
0.9708029197080292
[[89  1]
 [ 3 44]]


In [92]:
from sklearn.model_selection import cross_val_score
cross_val_score(regr2, x, y, cv=10)

array([0.92753623, 0.92753623, 0.95652174, 0.94202899, 0.97058824,
       0.95588235, 0.95588235, 0.97058824, 0.97058824, 0.98507463])